### ISSUE TITLE
Network interface base functions

### ISSUE THREAD

**Issue by RedbeanGit** [do3-2021/kudo#25]
### Is it a team issue or a project issue ?

Team issue

### Which teams are related to the feature request?

Networking

### What is the problem you're trying to solve?

Create a first implementation of the network service.

### Task list

- [ ] Implement functions to manage network interfaces
  - [ ] Function to create a network interface
  - [ ] Function to delete network interfaces
  - [ ] Function to list network interfaces
