### ISSUE TITLE
Define CLI API

### ISSUE THREAD

**Issue by NilsPonsard** [do3-2021/kudo#3]
### What is the problem you're trying to solve?

The client team need to define how the user and the user’s scripts will interact with the client.

### Task list

- [x] List the commands to define 
- [x] Define the arguments and logic of the commands (`docs/proposals/cli.md`)
- [x] Define exit code meaning
- [x] Define verbosity format "Error :", "Warning :" ....
- [x] define cli-convention.md
   
### commands features

- [x] Define global optionnal parameters
    - [x] config file location
    - [x] verbosity level
    - [ ] set config values (control plane ip, auth...)

For each command : 
- [ ] output format option
- [ ] help about the command

List commands : 
- [x] pagination
- [x] delimiter
- [x] header on|off

### TODO (Nils) : 

- [x] command apply
- [x] option no update
- [ ] env variables
- [x] document exit code 1
- [x] remove workload : remove instances

### Anything else ?

This work is very dependent on the external api of the controller.
