### ISSUE TITLE
feat: define project structure

### ISSUE THREAD

**Issue by lucido-simon** [do3-2021/kudo#30]
### What is the problem you're trying to solve?

Define basic structure for the project

### Task list

- [x] Create folder for protos
- [x] Create folder for each team
- [x] Init lib for protos
- [x] Import lib in all projects, except for the CLI
